
name: update-images 
run-name: Update ecr-image
on:
  workflow_dispatch:
jobs:
  create-actions:
    name: "build action runners"
    runs-on: ubuntu-24.04
    permissions: 
      packages: write
      contents: write
      id-token: write
      actions: write
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::354918371398:role/github-access-koa
        aws-region: eu-west-1
        role-skip-session-tagging: true

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registries: 354918371398
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v4
    - name: Test if any image needs update
      run: ./scripts/update-images.sh
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: 'apps/**'
        message: 'Updated images'
